loglevel: "info"
modbus:
  server: "tcp://10.51.12.45:502"
  readingsfile: "registers.csv"
  freqsec: 20
  singlereadcount: 120
http:
  data: "http://core-switch:8585/batch"
  alerts: "http://core-switch:8585/alerts"
