LogLevel: "Info"
MappingFile: "config.csv"
MQTT:
  Host: "tcp://192.168.1.10:1883"
  Port: 1883
  User: ""
  Pass: ""
HTTP:
  Data: "http://core-switch:8080/v3/data"
  Alerts: "http://core-switch:8080/v3/alerts"
  IdleTO: 5
  MaxIdle: 3
