loglevel: "INFO"
snmp:
  fetch_interval: 15
  connect_timeout: 10
  worker_count: 2
  devices_file: "config.csv"
  maps_folder: "./maps"
http:
  data_url: "http://core-switch:8585/v3/batch"
  alerts_url: "http://core-switch:8585/v3/alerts"
