package api

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/jackc/pgx/v5/pgxpool"
)

func registerHandler(pool *pgxpool.Pool, jwtSecret string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req struct {
			OrgName  string `json:"org_name"`
			Email    string `json:"email"`
			Password string `json:"password"`
		}
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil ||
			req.OrgName == "" || req.Email == "" || req.Password == "" {
			writeError(w, http.StatusBadRequest, "org_name, email and password required")
			return
		}

		ctx := context.Background()
		tx, err := pool.Begin(ctx)
		if err != nil {
			writeError(w, http.StatusInternalServerError, "db error")
			return
		}
		defer tx.Rollback(ctx)

		var orgID string
		if err := tx.QueryRow(ctx,
			`INSERT INTO organisations (name) VALUES ($1) RETURNING id`, req.OrgName,
		).Scan(&orgID); err != nil {
			writeError(w, http.StatusInternalServerError, "failed to create organisation")
			return
		}

		// Use pgcrypto crypt() with blowfish — compatible with both Go bcrypt verify
		// and pgcrypto crypt() verify. This keeps password hashing in the DB.
		var userID string
		if err := tx.QueryRow(ctx,
			`INSERT INTO users (org_id, email, password_hash, role)
			 VALUES ($1,$2,crypt($3, gen_salt('bf',12)),'admin') RETURNING id`,
			orgID, req.Email, req.Password,
		).Scan(&userID); err != nil {
			writeError(w, http.StatusConflict, "email already registered")
			return
		}

		if err := tx.Commit(ctx); err != nil {
			writeError(w, http.StatusInternalServerError, "commit failed")
			return
		}

		token, err := makeJWT(jwtSecret, userID, orgID, "admin")
		if err != nil {
			writeError(w, http.StatusInternalServerError, "token error")
			return
		}
		writeJSON(w, http.StatusCreated, map[string]any{
			"token":   token,
			"org_id":  orgID,
			"user_id": userID,
			"role":    "admin",
		})
	}
}

func loginHandler(pool *pgxpool.Pool, jwtSecret string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req struct {
			Email    string `json:"email"`
			Password string `json:"password"`
		}
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			writeError(w, http.StatusBadRequest, "invalid body")
			return
		}

		var userID, orgID, role string
		var pwMatch bool
		// Use pgcrypto crypt() to verify — works for all bcrypt hashes whether
		// generated by Go's bcrypt or PostgreSQL's gen_salt('bf')
		err := pool.QueryRow(context.Background(),
			`SELECT id, org_id, role,
			        (password_hash = crypt($2, password_hash)) AS pw_match
			 FROM users WHERE email=$1`, req.Email, req.Password,
		).Scan(&userID, &orgID, &role, &pwMatch)
		if err != nil || !pwMatch {
			writeError(w, http.StatusUnauthorized, "invalid credentials")
			return
		}

		token, err := makeJWT(jwtSecret, userID, orgID, role)
		if err != nil {
			writeError(w, http.StatusInternalServerError, "token error")
			return
		}
		writeJSON(w, http.StatusOK, map[string]any{"token": token, "org_id": orgID, "role": role})
	}
}
